parameters:
  # The platforms to bundle for
  - name: Platforms
    type: object

  # The configuration to bundle for
  - name: Configuration
    type: string

  # Whether to sign the output artifacts
  - name: SignOutput
    type: boolean

jobs:
  - job: Bundle_${{ parameters.Configuration }}
    pool:
      type: windows
    variables:
      runCodesignValidationInjection: false
      skipComponentGovernanceDetection: true
      ob_outputDirectory: $(Build.ArtifactStagingDirectory)\wingetstudio
      ob_artifactBaseName: msixbundle_${{ parameters.Configuration }}
    steps:
      # Download the MSIX artifacts
    - ${{ each platform in parameters.Platforms }}:
      - task: DownloadPipelineArtifact@2
        displayName: Download msix_${{ platform }}_${{ parameters.Configuration }}
        inputs:
          buildType: 'current'
          artifactName: msix_${{ platform }}_${{ parameters.Configuration }}
          targetPath: '$(ob_outputDirectory)'

      # Bundle the MSIX artifacts
    - template: /.pipelines/steps/build-msixbundle.yml@self
      parameters:
        Configuration: ${{ parameters.Configuration }}
        OutputDir: '$(ob_outputDirectory)'
        SignOutput: ${{ parameters.SignOutput }}