//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace WinGetStudio.Services.DesiredStateConfiguration.Models.DSCWinGetConfigurationV0_2
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Description of what these resources do to apply the desired state in the configuration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class DSCWinGetConfigurationV0_2
    {

        /// <summary>
        /// The properties of the configuration.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("properties")]
        public Properties Properties { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Properties
    {

        /// <summary>
        /// The preconditions required to run the configuration.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("assertions")]
        public System.Collections.Generic.List<Assertions> Assertions { get; set; }

        /// <summary>
        /// A list of resources (software, tools, packages, settings, etc.) to be included in the configuration.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("resources")]
        public System.Collections.Generic.List<Assertions> Resources { get; set; }

        /// <summary>
        /// Resources that retrieve information via a 'get' operation.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("parameters")]
        public System.Collections.Generic.List<Assertions> Parameters { get; set; }

        /// <summary>
        /// The configuration syntax version.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("configurationVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$")]
        public string ConfigurationVersion { get; set; } = "0.2.0";

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Assertions
    {

        /// <summary>
        /// The name of the resource. Optionally specify module and resource as module/resource.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("resource")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string Resource { get; set; }

        /// <summary>
        /// A unique identifier for this resource.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string Id { get; set; }

        /// <summary>
        /// The list of resource ids identifying dependencies.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dependsOn")]
        public System.Collections.Generic.List<string> DependsOn { get; set; }

        /// <summary>
        /// Information about the module and/or resource.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("directives")]
        public Directives Directives { get; set; }

        /// <summary>
        /// Parameters as key-value pairs to be passed to the resource.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("settings")]
        public object Settings { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Directives
    {

        /// <summary>
        /// The name of the module.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("module")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string Module { get; set; }

        /// <summary>
        /// The description of the desired state.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.StringLength(512)]
        public string Description { get; set; }

        /// <summary>
        /// Enable using prerelease modules.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("allowPrerelease")]
        public bool AllowPrerelease { get; set; }

        /// <summary>
        /// Provides an indication of the security context in which the configuration unit should be run.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("securityContext")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<DirectivesSecurityContext>))]
        public DirectivesSecurityContext SecurityContext { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum DirectivesSecurityContext
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"current")]
        Current = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"restricted")]
        Restricted = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"elevated")]
        Elevated = 2,


    }
}