//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace WinGetStudio.Services.DesiredStateConfiguration.Models.Schemas.ConfigurationV3
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Defines the data type for the parameter value.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum Json
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"string")]
        String = 0,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"securestring")]
        Securestring = 1,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"int")]
        Int = 2,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"bool")]
        Bool = 3,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"object")]
        Object = 4,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"secureobject")]
        Secureobject = 5,


        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"array")]
        Array = 6,


    }

    /// <summary>
    /// Defines a runtime option for a DSC Configuration Document.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Json3 : object
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Json>))]
        public Json Type { get; set; } = default!;

        /// <summary>
        /// Defines the default value for the parameter.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("defaultValue")]
        public object? DefaultValue { get; set; } = default!;

        /// <summary>
        /// Defines a list of valid values for the parameter. If the parameter is defined with any other values, it's invalid.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("allowedValues")]
        public System.Collections.Generic.List<object>? AllowedValues { get; set; } = default!;

        /// <summary>
        /// Defines a synopsis for the parameter explaining its purpose.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string? Description { get; set; } = default!;

        /// <summary>
        /// Defines a set of key-value pairs for the parameter. This metadata isn't validated.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("metadata")]
        public object? Metadata { get; set; } = default!;

    }

    /// <summary>
    /// Defines an instance of a DSC Resource in a configuration.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Json6
    {

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\w+(\.\w+){0,2}\/\w+$")]
        public string Type { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 1)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-zA-Z0-9 ]+$")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Defines a list of DSC Resource instances that DSC must successfully process before processing this instance. Each value for this property must be the `resourceID()` lookup for another instance in the configuration. Multiple instances can depend on the same instance, but every dependency for an instance must be unique in that instance's `dependsOn` property.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dependsOn")]
        public System.Collections.Generic.List<string>? DependsOn { get; set; } = default!;

        /// <summary>
        /// Defines the properties of the DSC Resource this instance manages. This property's value must be an object. DSC validates the property's value against the DSC Resource's schema.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("properties")]
        public object? Properties { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Describes a valid DSC Configuration Document.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ConfigurationV3
    {

        /// <summary>
        /// This property must be the canonical URL of the DSC Configuration Document schema that the document is implemented for.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("$schema")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<ConfigurationV3Schema>))]
        public ConfigurationV3Schema Schema { get; set; } = default!;

        /// <summary>
        /// Defines runtime options for the configuration. Users and integrating tools can override use the defined parameters to pass alternate values to the configuration.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("parameters")]
        public System.Collections.Generic.IDictionary<string, Json3>? Parameters { get; set; } = default!;

        /// <summary>
        /// Defines a set of reusable values for the configuration document. The names of this value's properties are the strings used to reference a variable's value.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("variables")]
        public object? Variables { get; set; } = default!;

        /// <summary>
        /// Defines a list of DSC Resource instances for the configuration to manage.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("resources")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.List<Json6> Resources { get; set; } = new System.Collections.Generic.List<Json6>();

        /// <summary>
        /// Defines a set of key-value pairs for the configuration. This metadata isn't validated.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("metadata")]
        public object? Metadata { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ConfigurationV3Schema
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json")]
        Https__raw_githubusercontent_com_PowerShell_DSC_main_schemas_2023_08_config_document_json = 0,


    }
}