//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


#nullable enable


namespace WinGetStudio.Services.DesiredStateConfiguration.Models.Schemas.WinGetConfigurationV01
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// A representation of a configuration used by an orchestrator for WinDSC.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class WinGetConfigurationV01
    {

        [System.Text.Json.Serialization.JsonPropertyName("properties")]
        public Properties? Properties { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Properties
    {

        [System.Text.Json.Serialization.JsonPropertyName("assertions")]
        public System.Collections.Generic.List<Assertions>? Assertions { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("resources")]
        public System.Collections.Generic.List<Assertions>? Resources { get; set; } = default!;

        /// <summary>
        /// Resources that retrieve information via a 'get' operation.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("parameters")]
        public System.Collections.Generic.List<Assertions>? Parameters { get; set; } = default!;

        /// <summary>
        /// The configuration syntax version.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("configurationVersion")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$")]
        public string ConfigurationVersion { get; set; } = "0.1.0";

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Assertions
    {

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("resource")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string Resource { get; set; } = default!;

        /// <summary>
        /// The identifier of this item.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string? Id { get; set; } = default!;

        /// <summary>
        /// The list of resource ids identifying dependencies.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dependsOn")]
        public System.Collections.Generic.List<string>? DependsOn { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("directives")]
        public Directives? Directives { get; set; } = default!;

        [System.Text.Json.Serialization.JsonPropertyName("settings")]
        public object? Settings { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Directives
    {

        /// <summary>
        /// The name of the module.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("module")]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string? Module { get; set; } = default!;

        /// <summary>
        /// The description of the desired state.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.StringLength(512)]
        public string? Description { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }
}